export const ROUTES = {
  Login: "Login",
  Home: "Home",
  Catalog: "Catalog",
  CatalogFilter: "CatalogFilter",
  PetInfo: "PetInfo",
  AdopterProfile: "AdopterProfile",
  OngProfile: "OngProfile",
  RegisterPet: "RegisterPet",
  EditPet: "EditPet",
  NotFound: "NotFound",
  FormSafeAdopter: "FormSafeAdopter",
  RegisterOng: "RegisterOng",
  EditUser: "EditUser",
  EditOrg: "EditOrg",
  Dashboard: "Dashboard",
  Terms: "Terms",
  Adoption: "Adoption",
  ResetPassword: "ResetPassword",
  ForgotPassword: "ForgotPassword",
  Settings: "Settings",
  HomeOng: "HomeOng",
  TestDraft: "TestDraft"
};
